### ISSUE TITLE
Missing instruction to initialise the Lucene index

### ISSUE THREAD

**Issue by ludovicc** [AMCeScience/Rosemary-Vanilla#4]
Hello,

I'm testing Rosemary with the command 'activator run'. When navigating to the site, I get the following error:

CreationException: Unable to create injector, see the following errors: 1) Error injecting constructor, org.apache.lucene.index.IndexNotFoundException: no segments* file found in NIOFSDirectory@/home/ludovic/Projects/_exploration/Rosemary/search lockFactory=NativeFSLockFactory@/home/ludovic/Projects/_exploration/Rosemary/search: files: [] at nl.amc.ebioscience.rosemary.services.search.SearchReader.<init>(SearchReader.scala:129) at nl.amc.ebioscience.rosemary.Module.configure(Module.scala:76) (via modules: com.google.inject.util.Modules$OverrideModule -> nl.amc.ebioscience.rosemary.Module) while locating nl.amc.ebioscience.rosemary.services.search.SearchReader for parameter 0 at nl.amc.ebioscience.rosemary.services.search.SearchWriter.<init>(SearchWriter.scala:35) at nl.amc.ebioscience.rosemary.Module.configure(Module.scala:75) (via modules: com.google.inject.util.Modules$OverrideModule -> nl.amc.ebioscience.rosemary.Module) while locating nl.amc.ebioscience.rosemary.services.search.SearchWriter 1 error

There was also an error about a missing /search folder, I fixed it by creating that folder manually but it looks like Lucene needs to perform some initialisation here.

Thanks

**Comment by shayanlinux** [comment]
Hi Ludovic, 
Thanks for the bug report, please remove the `/search` folder (or the `.lock` file inside) and Rosemary will take care of creating it and initialising it. The mechanism for directory creation and initialisation was there but was made ineffective because of a circular dependency injection made in a recent code change. The circular dependency injection is now fixed.
